FROM golang:1.26.3 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/operator ./cmd/operator

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /out/operator /operator

USER nonroot:nonroot
ENTRYPOINT ["/operator"]
