apiVersion: v1
kind: ServiceAccount
metadata:
  name: berth-apiserver
  namespace: berth-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: berth-apiserver
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: berth-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: berth-apiserver
subjects:
  - kind: ServiceAccount
    name: berth-apiserver
    namespace: berth-system
