apiVersion: v1
kind: ServiceAccount
metadata:
  name: berth-operator
  namespace: berth-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: berth-operator
rules:
  - apiGroups: ["berth.skaphos.io"]
    resources: ["berthleases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["berth.skaphos.io"]
    resources: ["berthleases/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: berth-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: berth-operator
subjects:
  - kind: ServiceAccount
    name: berth-operator
    namespace: berth-system
