{{- if .Values.tls.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "berth-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "berth-apiserver.labels" . | nindent 4 }}
spec:
  secretName: {{ include "berth-apiserver.tlsSecretName" . }}
  duration: {{ .Values.tls.certManager.duration | default "8760h" }}
  renewBefore: {{ .Values.tls.certManager.renewBefore | default "720h" }}
  commonName: {{ include "berth-apiserver.fullname" . }}
  dnsNames:
    - {{ include "berth-apiserver.fullname" . }}
    - {{ include "berth-apiserver.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "berth-apiserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.tls.certManager.dnsNames }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  issuerRef:
    {{- toYaml .Values.tls.certManager.issuerRef | nindent 4 }}
{{- end }}
