apiVersion: apps/v1
kind: Deployment
metadata:
  name: berth-apiserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: berth-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: berth-apiserver
    spec:
      containers:
        - name: apiserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
