{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "berth-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "berth-apiserver.labels" . | nindent 4 }}
spec:
  {{- if and .Values.podDisruptionBudget.maxUnavailable (not .Values.podDisruptionBudget.minAvailable) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "berth-apiserver.selectorLabels" . | nindent 6 }}
{{- end }}
