apiVersion: v1
kind: Service
metadata:
  name: {{ include "berth-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "berth-apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
    {{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "berth-apiserver.selectorLabels" . | nindent 4 }}
