{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berth-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "berth-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ trimPrefix ":" .Values.metrics.bindAddress | int }}
      targetPort: metrics
      protocol: TCP
      {{- if .Values.metrics.secure }}
      appProtocol: https
      {{- end }}
  selector:
    {{- include "berth-operator.selectorLabels" . | nindent 4 }}
{{- end }}
